# This will be in the developer-docs and user help repos only
name: 📖 Documentation issue
description: Report an issue regarding the documentation content
body:
  - type: markdown
    attributes:
      value: |
        We strongly encourage you to [submit a pull request](https://docs.silverstripe.org/en/contributing/documentation/) which resolves the issue.
        Issues which are accompanied with a pull request are a lot more likely to be resolved quickly.
  - type: textarea
    id: pages-affected
    attributes:
      label: Pages affected
      description: A list of links of pages which are affected by this issue
      placeholder: |

        - [Getting Started](https://docs.silverstripe.org/en/5/getting_started/)
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the problem you've found in the documentation
    validations:
      required: true
  - type: checkboxes
    id: validations
    attributes:
      label: Validations
      description: "Before submitting the issue, please make sure you do the following:"
      options:
        - label: Check that there isn't already an issue that reports the same problem
          required: true
